general:
    partposit_path: '.\partposit_file'
    temporary_file_path: '.\temporary'
    final_output_path: '.\output'
    target_region: [35, 25, 110, 130]   # '.\shp\boundary.shp' or [lat_up, lat_down, lon_left, lon_right]
    start_time: 2023073100
    end_time: 2023080100
    tracking_days: 3
    #hours
    time_span: 6
    #fixed in the current version
    output_spatial_resolution: 1

# default WaterSip setting
watersip:
    # kg/kg
    default_q_diff_p: -0.0002
    # kg/kg
    default_q_diff_e: 0.0002
    # %
    default_rh_threshold: 80
    # BLH scailing factor
    default_blh_factor: 1.5

#WarerSip-HAMSTER (include STEP 3, 4, 5, 6, 7)
warerSip-HAMSTER:
    observation_path: '.\P_E_observation'
    P_E_simulation_output_path: '.\P_E_simulation'
    #kg/kg 
    q_diff_p: -0.0002
    #kg/kg 
    q_diff_e: 0.0002
    #%, RH 
    rh_threshold: 80
    #BLH scailing factor 
    blh_factor: 1.5

#WarerSip-DF (include STEP 1, 2, 3, 4)
warerSip-DF:
    observation_path: '.\P_E_observation'
    DF_file_path: '.\DF'
    #used for select all potential E particles
    q_diff_e_df: 0.0000
    #used for select all potential P particles 
    q_diff_p_df: -0.0000

# WarerSip-DF-HAMSTER (include STEP 1, 2, 3, 4, 5, 6, 7)
warerSip-DF-HAMSTER:
    observation_path: '.\P_E_observation'
    DF_file_path: '.\DF'
    P_E_simulation_output_path: '.\P_E_simulation'
    #used for select all potential E particles 
    q_diff_e_df: 0.0000
    #used for select all potential P particles 
    q_diff_p_df: -0.0000

