General:
    partposit_path: 'G:\FLEXPART\output_2023'
    temporary_file_path: 'G:\FLEXPART\WaterSip-DF-HAMSTER\temporary'
    final_output_path: 'G:\FLEXPART\WaterSip-DF-HAMSTER\output'
    # '.\shp\boundary.shp' or [lat_up, lat_down, lon_left, lon_right]
    target_region: [41, 39, 119, 121]
    start_time: 2023073100
    end_time: 2023080100
    tracking_days: 3
    #hours
    time_span: 6
    #fixed in the current version
    output_spatial_resolution: 1
    # parallel number
    max_workers: 4    
    # Maximum number of cached files
    max_cache_size: 10

# WaterSip setting
WaterSip:
    # kg/kg
    q_diff_p: -0.0000
    # kg/kg
    q_diff_e: 0.0002
    # %
    rh_threshold: 80
    # BLH scailing factor
    blh_factor: 1.5

# WarerSip-HAMSTER (include STEP 3, 4, 5, 6, 7)
WaterSip-HAMSTER:
    observation_path: 'G:\FLEXPART\WaterSip-DF-HAMSTER\P_E_observation'
    P_E_simulation_output_path: 'G:\FLEXPART\WaterSip-DF-HAMSTER\P_E_simulation'
    #kg/kg 
    q_diff_p: -0.0000
    #kg/kg
    q_diff_e: 0.0002
    #%, RH
    rh_threshold: 80
    #BLH scailing factor
    blh_factor: 1.5
    #check whether updata P_E_simulation, choose 'flase' when use existing P_E_simulation files
    update_P_E_simulation: true

# WarerSip-DF (include STEP 1, 2, 3, 4)
WaterSip-DF:
    observation_path: 'G:\FLEXPART\WaterSip-DF-HAMSTER\P_E_observation'
    DF_file_path: 'G:\FLEXPART\WaterSip-DF-HAMSTER\DF'
    #used for select all potential E particles
    q_diff_e_df: 0.0000
    #used for select all potential P particles
    q_diff_p_df: -0.0000
    #check whether updata DF files, choose 'flase' when use existing DF files
    update_DF: true

# WarerSip-DF-HAMSTER (include STEP 1, 2, 3, 4, 5, 6, 7)
WaterSip-DF-HAMSTER:
    observation_path: 'G:\FLEXPART\WaterSip-DF-HAMSTER\P_E_observation'
    DF_file_path: 'G:\FLEXPART\WaterSip-DF-HAMSTER\DF'
    P_E_simulation_output_path: 'G:\FLEXPART\WaterSip-DF-HAMSTER\P_E_simulation'
    #used for select all potential E particles
    q_diff_e_df: 0.0000
    #used for select all potential P particles
    q_diff_p_df: -0.0000
    #check whether updata DF files, choose 'flase' when use existing DF files
    update_DF: ture
    #check whether updata P_E_simulation, choose 'flase' when use existing P_E_simulation files
    update_P_E_simulation: true
